export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_ERROR = 'FETCH_MOVIE_ERROR';
export const FETCH_MOVIE_START = 'FETCH_MOVIE_START';

export const FETCH_TVSHOWS_SUCCESS = 'FETCH_TVSHOW_SUCCESS';
export const FETCH_TVSHOWS_ERROR = 'FETCH_TVSHOW_ERROR';
export const FETCH_TVSHOWS_START = 'FETCH_TVSHOW_START';

export const FETCH_TVSHOW_INFO_SUCCESS = 'FETCH_TVSHOW_INFO_SUCCESS';
export const FETCH_TVSHOW_INFO_ERROR = 'FETCH_TVSHOW_INFO_ERROR';
export const FETCH_TVSHOW_EPISODES_SUCCESS = 'FETCH_TVSHOW_EPISODES_SUCCESS';
export const FETCH_TVSHOW_CAST_SUCCESS = 'FETCH_TVSHOW_CAST_SUCCESS';
export const SET_CURRENT_TVSHOW_SUCCESS = 'SET_CURRENT_TVSHOW_SUCCESS';