export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_ERROR = 'FETCH_MOVIE_ERROR';
export const FETCH_MOVIE_START = 'FETCH_MOVIE_START';

export const FETCH_TVSHOW_SUCCESS = 'FETCH_TVSHOW_SUCCESS';
export const FETCH_TVSHOW_ERROR = 'FETCH_TVSHOW_ERROR';
export const FETCH_TVSHOW_START = 'FETCH_TVSHOW_START';