export const Images = {
	agentcarter: 'app/TV Shows/Agent Carter.jpg',
	arrow: 'app/TV Shows/Arrow.jpg',
	avengersassemble: 'app/TV Shows/Avengers Assemble.jpg',
	bettercallsaul: 'app/TV Shows/Better Call Saul.jpg',
	breakingbad: 'app/TV Shows/Breaking Bad.jpg',
	brooklynninenine: 'app/TV Shows/Brooklyn Nine Nine.jpg',
	daredevil: 'app/TV Shows/DareDevil.jpg',
	flash: 'app/TV Shows/Flash.jpg',
	gameofthrones:'app/TV Shows/Game Of Thrones.jpg',
	gotham: 'app/TV Shows/Gotham.jpg',
	ironfist:'app/TV Shows/Iron Fist.jpg',
	jessicajones:'app/TV Shows/Jessica Jones.jpg',
	legendsoftomorrow:'app/TV Shows/Legends Of Tomorrow.jpg',
	limitless: 'app/TV Shows/Limitless.jpg',
	lukecage: 'app/TV Shows/Luke Cage.jpg',
	narcos: 'app/TV Shows/Narcos.jpg',
	manwithaplan: 'app/TV Shows/Man with a Plan.jpg',
	onepiece: 'app/TV Shows/One Piece.jpg',
	onepunchman: 'app/TV Shows/One Punch Man.jpg',
	siliconvalley: 'app/TV Shows/Silicon Valley.jpg',
	suits: 'app/TV Shows/Suits.jpg',
	themusketeers: 'app/TV Shows/The Musketeers.jpg',
	supernatural: 'app/TV Shows/Supernatural.jpg',
	themusketeers: 'app/TV Shows/The Musketeers.jpg',
	vixen: 'app/TV Shows/Vixen.jpg',
	whitecollar: 'app/TV Shows/White Collar.jpg'
}